MODUL-991 - Change name/value of Z_INDEX_DEFAULT const,
ulaval/modul-components pull request #966
Opened 2019-05-10 18:01 UTC by fredduguay

## `@ulaval/modul-components`
# PR Checklist

- [x] Provide a small description of the changes introduced by this PR
Since the storybook content is injected into an iframe, z-index isn't always working as intended and it is possible to click the RTE through the modal's backdrop (storybook only).

However, while it works correctly in the sandboxes, the z-index of the RTE elements shouldn't be higher than the Z_INDEX_DEFAULT const declared in the modul.ts file.

Z_INDEZ_DEFAULT is being renamed to Z_INDEX_DEFAULT since it had a typo and it's value is being increased from 100 to 999 in order for the portal element to always be the top layer when multiple elements are positioned in absolute.

This fix will allow the backdrop to remain the top layer in both cases when it is either being injected in an iframe or in regular fashin. It will also make it less likely for other components to come out on top.
- [x] Include links to issues
https://jira.dti.ulaval.ca/browse/MODUL-991
- [ ] Openshift deployment requested

- [ ] Include this section in the release notes

- [ ] Other info

2019-05-10 18:04 UTC, sioue19 approved these changes

2019-05-10 19:02 UTC, raphpare approved these changes

2019-05-13 14:18 UTC, jomat76 approved these changes

2019-05-23 14:14 UTC, chuckmah approved these changes

2019-05-23 14:30 UTC, chuckmah commented
@fredduguay 

Je suis pas certain de voir les impacts visuels que le bugfix va causé donc j'ai enlevé le flag breaking change UI 

j'ai raison?

2019-05-23 19:51 UTC, jipigi commented
Les problème qu'on avait sont corrigé :) 
J'ai rencontré le bogue suivant lors de mes tests. Pour reproduire :
- Mettre en plein écran 
- Cliquer sur Ajouter une image
- Fermer la fenêtre secondaire
- Quitter le mode plein écran

On voit que la fenêtre d'ajout d'image n'a pas été fermée.
![sn6uQAqgSx](https://user-images.githubusercontent.com/35844644/58282059-a3d68700-7d72-11e9-9ace-14ec4c0c7e2d.gif)

2019-05-28 13:53 UTC, cabob approved these changes

2019-05-28 14:12 UTC, fredduguay commented
> @fredduguay
> 
> Je suis pas certain de voir les impacts visuels que le bugfix va causé donc j'ai enlevé le flag breaking change UI
> 
> j'ai raison?

Cétait surtout une précaution, je crois que les chances de causer un breaking chance sont très minimes. Je crois qu'il faut cependant tester ceci convenablement avant de merger.

2019-05-30 13:21 UTC, jipigi requested changes
Voir le bogue décrit ci-dessus.

2019-06-14 14:59 UTC, chuckmah commented
@jipigi  le problème semble au niveau des css froela voir->

https://github.com/froala/wysiwyg-editor/blob/30338bede5867ce08c9b0fd50801f8a97b02a5c7/css/froala_editor.css#L594

est-ce qu'on bloque ce PR ou on ouvre un nouveau ticket?

2022-04-20 19:03 UTC, closed without merging